### ISSUE TITLE
Error injecting data sources

### ISSUE THREAD

**Issue by santoshreddy17** [kumuluz/kumuluzee-testing#2]
We are having issues injecting datasources using 
 <dependency>
            <groupId>com.kumuluz.ee.testing</groupId>
            <artifactId>kumuluzee-arquillian-container</artifactId>
            <version>1.0.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.jboss.arquillian.junit</groupId>
            <artifactId>arquillian-junit-container</artifactId>
            <version>1.4.0.Final</version>
            <scope>test</scope>
        </dependency>
**Exception we get** 
Exception in thread "main" java.lang.RuntimeException: Failed to load class of driverClassName [org.postgresql.Driver] in either of HikariConfig class loader or Thread context classloader
        at com.zaxxer.hikari.HikariConfig.setDriverClassName(HikariConfig.java:334)
        at com.kumuluz.ee.EeApplication.initialize(EeApplication.java:262)
        at com.kumuluz.ee.EeApplication.<init>(EeApplication.java:73)
        at com.kumuluz.ee.testing.arquillian.assets.MainWrapper.main(MainWrapper.java:44)

**Some research pointed us to -**
https://github.com/brettwooldridge/HikariCP/issues/982

And looks like it is an issue with Hikari dependency. 
We tried using the suggested version by excluding and including the one which they said has fixed the issue but still get the same exception.

Any suggestions ?

**Comment by urbim** [comment]
It seems like the Postgres driver is missing in the deployment. I assume you are using the `MavenDependencyAppender` mechanism to add dependencies to the deployment.

Can you check if the Postgres driver is missing in the appender?
